FORMAT: 1A
HOST: http://apics.oracle.com:8001/

# Energy25

This is Energy 25 API. 

## Questions Collection [/Energy25/current/usage/month]

### Get Current Usage [GET]

+ Response 200 (application/json)

        [
            {
                "customer": "1568",
                
            }
        ]


        }